apiVersion: v1
kind: Service
metadata:
  name: go-app-with-devops-service
spec:
  selector:
    app: go-app-with-devops
  ports:
    - protocol: TCP
      port: 90
      targetPort: 90
  type: ClusterIP
  